export const comunas = {
  comunas: [
    { slug: "algarrobo", name: "algarrobo" },
    { slug: "alhue", name: "alhué" },
    { slug: "alto-biobio", name: "alto biobío" },
    { slug: "alto-del-carmen", name: "alto del carmen" },
    { slug: "alto-hospicio", name: "alto hospicio" },
    { slug: "ancud", name: "ancud" },
    { slug: "andacollo", name: "andacollo" },
    { slug: "angol", name: "angol" },
    { slug: "antofagasta", name: "antofagasta" },
    { slug: "antuco", name: "antuco" },
    { slug: "arauco", name: "arauco" },
    { slug: "arica", name: "arica" },
    { slug: "buin", name: "buin" },
    { slug: "bulnes", name: "bulnes" },
    { slug: "cabildo", name: "cabildo" },
    { slug: "cabo-de-hornos", name: "cabo de hornos" },
    { slug: "cabrero", name: "cabrero" },
    { slug: "calama", name: "calama" },
    { slug: "calbuco", name: "calbuco" },
    { slug: "caldera", name: "caldera" },
    { slug: "calera", name: "calera" },
    { slug: "calle-larga", name: "calle larga" },
    { slug: "camarones", name: "camarones" },
    { slug: "camina", name: "camiña" },
    { slug: "canela", name: "canela" },
    { slug: "canete", name: "cañete" },
    { slug: "carahue", name: "carahue" },
    { slug: "cartagena", name: "cartagena" },
    { slug: "casablanca", name: "casablanca" },
    { slug: "castro", name: "castro" },
    { slug: "catemu", name: "catemu" },
    { slug: "cauquenes", name: "cauquenes" },
    { slug: "cerrillos", name: "cerrillos" },
    { slug: "cerro-navia", name: "cerro navia" },
    { slug: "chaiten", name: "chaitén" },
    { slug: "chanco", name: "chanco" },
    { slug: "chepica", name: "chepica" },
    { slug: "chiguayante", name: "chiguayante" },
    { slug: "chile-chico", name: "chile chico" },
    { slug: "chillan", name: "chillán" },
    { slug: "chillan-viejo", name: "chillán viejo" },
    { slug: "chimbarongo", name: "chimbarongo" },
    { slug: "cholchol", name: "cholchol" },
    { slug: "chonchi", name: "chonchi" },
    { slug: "cisnes", name: "cisnes" },
    { slug: "cobquecura", name: "cobquecura" },
    { slug: "cochamo", name: "cochamó" },
    { slug: "cochrane", name: "cochrane" },
    { slug: "codegua", name: "codegua" },
    { slug: "coelemu", name: "coelemu" },
    { slug: "coihaique", name: "coihaique" },
    { slug: "coinco", name: "coinco" },
    { slug: "colbun", name: "colbún" },
    { slug: "colchane", name: "colchane" },
    { slug: "colina", name: "colina" },
    { slug: "collipulli", name: "collipulli" },
    { slug: "coltauco", name: "coltauco" },
    { slug: "combarbala", name: "combarbalá" },
    { slug: "concepcion", name: "concepción" },
    { slug: "conchali", name: "conchalí" },
    { slug: "constitucion", name: "constitución" },
    { slug: "contulmo", name: "contulmo" },
    { slug: "copiago", name: "copiapó" },
    { slug: "coquimbo", name: "coquimbo" },
    { slug: "coronel", name: "coronel" },
    { slug: "corral", name: "corral" },
    { slug: "coyhaique", name: "coyhaique" },
    { slug: "cunco", name: "cunco" },
    { slug: "curacautin", name: "curacautín" },
    { slug: "curacavi", name: "curacaví" },
    { slug: "curaco-de-velez", name: "curaco de vélez" },
    { slug: "curanilahue", name: "curanilahue" },
    { slug: "curarreheue", name: "curarreheue" },
    { slug: "curepto", name: "curepto" },
    { slug: "curico", name: "curicó" },
    { slug: "dalcahue", name: "dalcahue" },
    { slug: "diego-de-almagro", name: "diego de almagro" },
    { slug: "el-bosque", name: "el bosque" },
    { slug: "el-carmen", name: "el carmen" },
    { slug: "el-monte", name: "el monte" },
    { slug: "el-quisco", name: "el quisco" },
    { slug: "el-tabo", name: "el tabo" },
    { slug: "empedrado", name: "empedrado" },
    { slug: "ercilla", name: "ercilla" },
    { slug: "estacion-central", name: "estación central" },
    { slug: "florida", name: "florida" },
    { slug: "freire", name: "freire" },
    { slug: "freirina", name: "freirina" },
    { slug: "fresia", name: "fresia" },
    { slug: "frutillar", name: "frutillar" },
    { slug: "futaleufu", name: "futaleufú" },
    { slug: "galvarino", name: "galvarino" },
    { slug: "general-lagos", name: "general lagos" },
    { slug: "gorbea", name: "gorbea" },
    { slug: "graneros", name: "graneros" },
    { slug: "guaitecas", name: "guaitecas" },
    { slug: "hijuelas", name: "hijuelas" },
    { slug: "hualane", name: "hualañé" },
    { slug: "hualpen", name: "hualpén" },
    { slug: "hualqui", name: "hualqui" },
    { slug: "huara", name: "huara" },
    { slug: "huasco", name: "huasco" },
    { slug: "huechuraba", name: "huechuraba" },
    { slug: "illapel", name: "illapel" },
    { slug: "independencia", name: "independencia" },
    { slug: "iquique", name: "iquique" },
    { slug: "isla-de-maipo", name: "isla de maipo" },
    { slug: "isla-de-pascua", name: "isla de pascua" },
    { slug: "juan-fernandez", name: "juan fernández" },
    { slug: "la-cisterna", name: "la cisterna" },
    { slug: "la-cruz", name: "la cruz" },
    { slug: "la-estrella", name: "la estrella" },
    { slug: "la-florida", name: "la florida" },
    { slug: "la-granja", name: "la granja" },
    { slug: "la-higuera", name: "la higuera" },
    { slug: "la-ligua", name: "la ligua" },
    { slug: "la-pintana", name: "la pintana" },
    { slug: "la-reina", name: "la reina" },
    { slug: "la-serena", name: "la serena" },
    { slug: "la-union", name: "la unión" },
    { slug: "lago-ranco", name: "lago ranco" },
    { slug: "lago-verde", name: "lago verde" },
    { slug: "laguna-blanca", name: "laguna blanca" },
    { slug: "laja", name: "laja" },
    { slug: "lampa", name: "lampa" },
    { slug: "lanco", name: "lanco" },
    { slug: "las-cabras", name: "las cabras" },
    { slug: "las-condes", name: "las condes" },
    { slug: "lautaro", name: "lautaro" },
    { slug: "lebu", name: "lebu" },
    { slug: "licanten", name: "licantén" },
    { slug: "limache", name: "limache" },
    { slug: "linares", name: "linares" },
    { slug: "litueche", name: "litueche" },
    { slug: "llailay", name: "llailay" },
    { slug: "llanquihue", name: "llanquihue" },
    { slug: "lo-barnechea", name: "lo barnechea" },
    { slug: "lo-espejo", name: "lo espejo" },
    { slug: "lo-prado", name: "lo prado" },
    { slug: "lolol", name: "lolol" },
    { slug: "loncoche", name: "loncoche" },
    { slug: "longavi", name: "longaví" },
    { slug: "lonquimay", name: "lonquimay" },
    { slug: "los-alamos", name: "los alamos" },
    { slug: "los-andes", name: "los andes" },
    { slug: "los-angeles", name: "los angeles" },
    { slug: "los-lagos", name: "los lagos" },
    { slug: "los-muermos", name: "los muermos" },
    { slug: "los-sauces", name: "los sauces" },
    { slug: "los-vilos", name: "los vilos" },
    { slug: "lota", name: "lota" },
    { slug: "lumaco", name: "lumaco" },
    { slug: "machali", name: "machalí" },
    { slug: "macul", name: "macul" },
    { slug: "mafil", name: "mafil" },
    { slug: "maipu", name: "maipú" },
    { slug: "malloa", name: "malloa" },
    { slug: "marchihue", name: "marchihue" },
    { slug: "maria-elena", name: "maría elena" },
    { slug: "maria-pinto", name: "maría pinto" },
    { slug: "mariquina", name: "mariquina" },
    { slug: "maule", name: "maule" },
    { slug: "maullin", name: "maullín" },
    { slug: "mejillones", name: "mejillones" },
    { slug: "melipeuco", name: "melipeuco" },
    { slug: "melipilla", name: "melipilla" },
    { slug: "molina", name: "molina" },
    { slug: "monte-patria", name: "monte patria" },
    { slug: "mostazal", name: "mostazal" },
    { slug: "mulchen", name: "mulchén" },
    { slug: "nacimiento", name: "nacimiento" },
    { slug: "nancagua", name: "nancagua" },
    { slug: "navidad", name: "navidad" },
    { slug: "negrete", name: "negrete" },
    { slug: "ninhue", name: "ninhue" },
    { slug: "niquen", name: "ñiquén" },
    { slug: "nunoa", name: "ñuñoa" },
    { slug: "olivar", name: "olivar" },
    { slug: "ollague", name: "ollagüe" },
    { slug: "olmue", name: "olmue" },
    { slug: "osorno", name: "osorno" },
    { slug: "ovalle", name: "ovalle" },
    { slug: "padre-hurtado", name: "padre hurtado" },
    { slug: "padre-las-casas", name: "padre las casas" },
    { slug: "paihuano", name: "paihuano" },
    { slug: "paillaco", name: "paillaco" },
    { slug: "paine", name: "paine" },
    { slug: "palena", name: "palena" },
    { slug: "palmilla", name: "palmilla" },
    { slug: "panguipulli", name: "panguipulli" },
    { slug: "panquehue", name: "panquehue" },
    { slug: "papudo", name: "papudo" },
    { slug: "paredones", name: "paredones" },
    { slug: "parral", name: "parral" },
    { slug: "pedro-aguirre-cerda", name: "pedro aguirre cerda" },
    { slug: "pelarco", name: "pelarco" },
    { slug: "pelluhue", name: "pelluhue" },
    { slug: "peralillo", name: "peralillo" },
    { slug: "penaflor", name: "peñaflor" },
    { slug: "penalolen", name: "peñalolén" },
    { slug: "perquenco", name: "perquenco" },
    { slug: "petorca", name: "petorca" },
    { slug: "peumo", name: "peumo" },
    { slug: "pica", name: "pica" },
    { slug: "pichidegua", name: "pichidegua" },
    { slug: "pichilemu", name: "pichilemu" },
    { slug: "pinto", name: "pinto" },
    { slug: "pirque", name: "pirque" },
    { slug: "piteo", name: "piteo" },
    { slug: "placilla", name: "placilla" },
    { slug: "pucon", name: "pucón" },
    { slug: "puente-alto", name: "puente alto" },
    { slug: "puerto-montt", name: "puerto montt" },
    { slug: "puerto-octay", name: "puerto octay" },
    { slug: "puerto-varas", name: "puerto varas" },
    { slug: "pumanque", name: "pumanque" },
    { slug: "punta-arenas", name: "punta arenas" },
    { slug: "punta-lavapie", name: "punta lavapié" },
    { slug: "punitaqui", name: "punitaqui" },
    { slug: "puren", name: "puren" },
    { slug: "purranque", name: "purranque" },
    { slug: "puyehue", name: "puyehue" },
    { slug: "queilen", name: "queilén" },
    { slug: "quilaco", name: "quilaco" },
    { slug: "quilicura", name: "quilicura" },
    { slug: "quilleco", name: "quilleco" },
    { slug: "quillon", name: "quillón" },
    { slug: "quillota", name: "quillota" },
    { slug: "quilpue", name: "quilpué" },
    { slug: "quinchao", name: "quinchao" },
    { slug: "quinquihue", name: "quinquihue" },
    { slug: "quinta-de-tilcoco", name: "quinta de tilcoco" },
    { slug: "quinta-normal", name: "quinta normal" },
    { slug: "quintero", name: "quintero" },
    { slug: "quirihue", name: "quirihue" },
    { slug: "rancagua", name: "rancagua" },
    { slug: "ranquil", name: "ránquil" },
    { slug: "rauco", name: "rauco" },
    { slug: "recoleta", name: "recoleta" },
    { slug: "renaico", name: "renaico" },
    { slug: "renca", name: "renca" },
    { slug: "rengo", name: "rengo" },
    { slug: "requinoa", name: "requinoa" },
    { slug: "retiro", name: "retiro" },
    { slug: "rio-bueno", name: "río bueno" },
    { slug: "rio-claro", name: "río claro" },
    { slug: "rio-hurtado", name: "río hurtado" },
    { slug: "rio-ibanez", name: "río ibáñez" },
    { slug: "rio-negro", name: "río negro" },
    { slug: "rio-verde", name: "río verde" },
    { slug: "romeral", name: "romeral" },
    { slug: "saavedra", name: "saavedra" },
    { slug: "sagrada-familia", name: "sagrada familia" },
    { slug: "salamanca", name: "salamanca" },
    { slug: "san-antonio", name: "san antonio" },
    { slug: "san-bernardo", name: "san bernardo" },
    { slug: "san-carlos", name: "san carlos" },
    { slug: "san-clemente", name: "san clemente" },
    { slug: "san-esteban", name: "san esteban" },
    { slug: "san-fabian", name: "san fabián" },
    { slug: "san-felipe", name: "san felipe" },
    { slug: "san-fernando", name: "san fernando" },
    { slug: "san-gregorio", name: "san gregorio" },
    { slug: "san-ignacio", name: "san ignacio" },
    { slug: "san-javier", name: "san javier" },
    { slug: "san-joaquin", name: "san joaquín" },
    { slug: "san-jose-de-maipo", name: "san josé de maipo" },
    { slug: "san-juan-de-la-costa", name: "san juan de la costa" },
    { slug: "san-miguel", name: "san miguel" },
    { slug: "san-nicolas", name: "san nicolás" },
    { slug: "san-pedro", name: "san pedro" },
    { slug: "san-pedro-de-atacama", name: "san pedro de atacama" },
    { slug: "san-pedro-de-la-paz", name: "san pedro de la paz" },
    { slug: "san-rafael", name: "san rafael" },
    { slug: "san-ramon", name: "san ramón" },
    { slug: "san-rosendo", name: "san rosendo" },
    { slug: "santa-barbara", name: "santa bárbara" },
    { slug: "santa-cruz", name: "santa cruz" },
    { slug: "santa-juana", name: "santa juana" },
    { slug: "santa-maria", name: "santa maría" },
    { slug: "santiago", name: "santiago" },
    { slug: "santo-domingo", name: "santo domingo" },
    { slug: "sierra-gorda", name: "sierra gorda" },
    { slug: "talagante", name: "talagante" },
    { slug: "talcahuano", name: "talcahuano" },
    { slug: "talcahuano-viejo", name: "talcahuano viejo" },
    { slug: "taltal", name: "taltal" },
    { slug: "temuco", name: "temuco" },
    { slug: "tepual", name: "tepual" },
    { slug: "teodoro-schmidt", name: "teodoro schmidt" },
    { slug: "tierra-amarilla", name: "tierra amarilla" },
    { slug: "tiltil", name: "tiltil" },
    { slug: "tocopilla", name: "tocopilla" },
    { slug: "tolten", name: "tolten" },
    { slug: "tome", name: "tomé" },
    { slug: "torres-del-paine", name: "torres del paine" },
    { slug: "tortel", name: "tortel" },
    { slug: "trauco", name: "trauco" },
    { slug: "trehuaco", name: "trehuaco" },
    { slug: "tucapel", name: "tucapel" },
    { slug: "valdivia", name: "valdivia" },
    { slug: "vicuna", name: "vicuña" },
    { slug: "victoria", name: "victoria" },
    { slug: "vilcun", name: "vilcún" },
    { slug: "villa-alegre", name: "villa alegre" },
    { slug: "villa-alemana", name: "villa alemana" },
    { slug: "villarrica", name: "villarrica" },
    { slug: "vina-del-mar", name: "viña del mar" },
    { slug: "vitacura", name: "vitacura" },
    { slug: "yumbel", name: "yumbel" },
    { slug: "yungay", name: "yungay" },
    { slug: "zapallar", name: "zapallar" },
  ],
};
